name: Sample Copilot CI Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Backend Tests
        run: |
          cd backend
          npm install
          npm test
      - name: Frontend Build
        run: |
          cd frontend
          npm install
          npm run build